name: Portfolio Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your code
      - name: Checkout
        uses: actions/checkout@v3  # It's better to use v3 instead of v1 if possible

      # 2) (Optional) Force Update AWS CLI
      - name: Install AWS CLI v2
        run: |
          # Remove any existing AWS CLI to avoid conflicts
          sudo rm -rf /usr/local/aws-cli
          sudo rm -rf /usr/local/bin/aws

          # Download, unzip, and install AWS CLI v2
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

          # Verify installation
          aws --version

      # 3) Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # 4) Deploy static site to S3 (or run other AWS commands)
      - name: Deploy static site to S3 bucket
        run: |
          aws s3 sync ./build s3://your-bucket-name
          aws s3 ls s3://sak-portfolio
